In [49]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [6]:
print(w2n.word_to_num('five'))


5


In [29]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [37]:
df.experience = df.fillna({
    'experience':'zero'
})

In [33]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].median())

In [35]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)

In [38]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [47]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [51]:
# creating our model object
reg = linear_model.LinearRegression()

In [52]:
# training our model with the given data set
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [54]:
# Our model is trained, let's predict the value
reg.predict([[2,9,6]])

array([53205.96797671])

In [55]:
reg.predict([[12, 10, 10]])

array([92002.18340611])

In [56]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [57]:
reg.intercept_

17737.26346433771

In [59]:
2812.95*12+1845.70*10+2205.24*10+17737.26

92002.05999999998